// AUTO-GENERATED image map (imageName -> require). Regenerate if assets change.
import type {ImageSourcePropType} from "react-native";

export const images: Record<string, ImageSourcePropType> = {
  "banner_computers": require("./banner_computers.jpg"),
  "banner_cosmetics": require("./banner_cosmetics.jpg"),
  "banner_gadgets": require("./banner_gadgets.jpg"),
  "banner_home": require("./banner_home.jpg"),
  "bikini": require("./bikini.jpg"),
  "cat_accessories": require("./cat_accessories.png"),
  "cat_appliances": require("./cat_appliances.png"),
  "cat_auto": require("./cat_auto.png"),
  "cat_baby": require("./cat_baby.png"),
  "cat_beauty": require("./cat_beauty.png"),
  "cat_books": require("./cat_books.png"),
  "cat_electronics": require("./cat_electronics.png"),
  "cat_food": require("./cat_food.png"),
  "cat_furniture": require("./cat_furniture.png"),
  "cat_home": require("./cat_home.png"),
  "cat_jewelry": require("./cat_jewelry.png"),
  "cat_kids": require("./cat_kids.png"),
  "cat_men": require("./cat_men.png"),
  "cat_pets": require("./cat_pets.png"),
  "cat_shoes": require("./cat_shoes.png"),
  "cat_sport": require("./cat_sport.png"),
  "cat_tools": require("./cat_tools.png"),
  "cat_women": require("./cat_women.png"),
  "pedicure": require("./pedicure.jpg"),
  "qa_catalog": require("./qa_catalog.jpg"),
  "qa_china": require("./qa_china.jpg"),
  "qa_fast": require("./qa_fast.jpg"),
  "qa_installment": require("./qa_installment.jpg"),
  "qa_kz": require("./qa_kz.jpg"),
  "qa_select": require("./qa_select.jpg"),
  "silverWatch": require("./silverWatch.jpg"),
  "swimwear": require("./swimwear.jpg"),
  "wallet": require("./wallet.jpg"),
  "watch": require("./watch.jpg"),
};
